version: "3"
services:
  api:
    image: dev-api
    build:
      context: .
      target: dev
    command: sh -c "/docker-entrypoint.sh"
    ports:
      - 8000:5000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django-docker
    volumes:
      - ~/dockerdata/django-docker_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine

  celery:
    image: celery-worker
    build:
      context: .
      target: celery
    command: sh -c "/docker-entrypoint-celery.sh"
    depends_on:
      - redis
      - db